var data=[
	[
		'熟练掌握各类语义化标签',
		'熟悉对各种标签特性及其相互转换',
		'H5拖拽、视频音频',
		'表格，H5新增表单等……'
	],
	[
		
		'掌握浮动及文档流特性',
		'熟练使用定位，掌握浏览器兼容性',
		'熟练掌握css3各种动画、盒模型样式',
		'移动端响应式'
	],
	[
		'了解数据类型、作用域闭包等语言特性',
		'掌握定时器、递归及数组字符串去重等',
		'掌握DOMBOMEVENT、JS兼容性、ECMA6',
		'了解正则表达式，ajax，面向对象编程'
	]
]
var spanText=[
			'鼠标移动方块消失图片显示',
			'动态设置方块样式',
			'模拟QQ对话',
			'商品计价器',
			'修改文件名称',
			'简易计算器',
			'简易QQ列表',
			'QQ音乐单选多选列表',
			'点击按钮V型旋转',
			'放大镜效果',
			'淘宝五星评分',
			'炫酷时钟',
			'多组图片切换',
			'图片Tab和List自动轮播',
			'日历',
			'唯美图片轮播',
			'查找替换文字',
			'js模拟select菜单',
			'图片自动轮播加文字说明',
			'键盘控制图片按方向切换',
			'简易版表格(添加、删除、移动……)',
			'关键字提示说明',
			'图片碰撞检测',
			'简易版超级玛丽游戏',
			'模拟鼠标滚轮',
			'指定位置图片放大效果',
			'H5音频频率效果',
			'UE首页(响应式)',
			'淘宝首页',
			'国美首页',
			'国美list页',
			'国美list页',
			'微云',
			'个人网站'
];
var href=[
			'https://mariotry.github.io/EraseBlock/',
			'https://mariotry.github.io/div/',
			'https://mariotry.github.io/phone/',
			'https://mariotry.github.io/goodsjishuqi/',
			'https://mariotry.github.io/changeText/',
			'https://mariotry.github.io/calculator/',
			'https://mariotry.github.io/qqlist/',
			'https://mariotry.github.io/bdmusic/',
			'https://mariotry.github.io/v/',
			'https://mariotry.github.io/magnifier/',
			'https://mariotry.github.io/bdpingfen/',
			'https://mariotry.github.io/watch/',
			'https://mariotry.github.io/duozutupian/',
			'https://mariotry.github.io/picgo/',
			'https://mariotry.github.io/calendar/',
			'https://mariotry.github.io/option/',
			'https://mariotry.github.io/find replace/',
			'https://mariotry.github.io/select/',
			'https://mariotry.github.io/carousel figure/',
			'https://mariotry.github.io/keyboard pic/',
			'https://mariotry.github.io/table/',
			'https://mariotry.github.io/prompt box/',
			'https://mariotry.github.io/collision/',
			'https://mariotry.github.io/mario/',
			'https://mariotry.github.io/scroll/',
			'https://mariotry.github.io/enlarge pic/',
			'https://mariotry.github.io/audio/',
			'https://mariotry.github.io/ue/',
			'https://mariotry.github.io/tb/',
			'https://mariotry.github.io/gm1/',
			'https://mariotry.github.io/gm2/',
			'https://mariotry.github.io/gm3/',
			'https://mariotry.github.io/vy/'
			
];